### PR TITLE
docs(eclib): add jsdoc generated documentation

### PR DESCRIPTION
**Pull request by MichaelZapataScality**
Update README to reflect that change
Add `npm run doc` routine to regenerate doc on the fly

### CODE REVIEW

**Comment by vrancurel** [comment]
purely cosmetic remark, he protobufjs is really more beautiful: http://htmlpreview.github.io/?https://raw.githubusercontent.com/dcodeIO/ProtoBuf.js/master/docs/ProtoBuf.html

**Comment by adrienverge** [comment]
Great job.

I wish there was a way to do this without sourcing all generated HTML in our VCS... but I did not find any.

Could you just add a `doc/README.md` or equivalent to indicate the command used to generate the doc?

**Comment by MichaelZapataScality** [comment]
@adrienverge came up with a better solution to host the documentation.

It's available on http://scality.github.io/eclib and should be updated automatically.

**Comment by DavidPineauScality** [comment]
Great, nice idea @adrienverge, and well done @MichaelZapataScality

**Comment by adrienverge** [comment]
Done! Thanks @MichaelZapataScality for initiating this.

**Pull request merged**
